<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Truss.Monads.Results\Truss.Monads.Results.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Google.Protobuf" Version="[3.13.0, 4)" />
      <PackageReference Include="Grpc.Tools" Version="2.62.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <Protobuf Include="results.proto" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="*.proto">
            <Pack>true</Pack>
            <PackagePath>contentFiles/any/any/proto</PackagePath>
        </Content>
    </ItemGroup>

</Project>
