<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Truss.Modeling.Application.MediatR\Truss.Modeling.Application.MediatR.csproj" />
      <ProjectReference Include="..\Truss.Modeling.Application\Truss.Modeling.Application.csproj" />
      <ProjectReference Include="..\Truss.Modeling.Domain\Truss.Modeling.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="1.0.0" />
    </ItemGroup>

</Project>
