<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <LangVersion>latest</LangVersion>
        <TargetFrameworks Condition="'$(OS)' == 'Windows_NT'">net8.0;net6.0;net7.0;net461;net48</TargetFrameworks>
        <TargetFrameworks Condition="'$(OS)' != 'Windows_NT'">net8.0;net6.0;net7.0;</TargetFrameworks>
    </PropertyGroup>
    
    <ItemGroup Condition="'$(TargetFramework)' == 'net461' or '$(TargetFramework)' == 'net48' ">
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="[1, 5)" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net6.0' or '$(TargetFramework)' == 'net7.0' or '$(TargetFramework)' == 'net8.0'">
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="[7, 10)" />
    </ItemGroup>
    
    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="[12, 14)" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.3.2" />
        <PackageReference Include="xunit" Version="2.7.1" />
        <PackageReference Include="xunit.runner.visualstudio" Version="[2.0.0, 2.4.5)">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector" Version="3.1.2">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\Truss.Modeling.Application\Truss.Modeling.Application.csproj" />
      <ProjectReference Include="..\Truss.Modeling.Domain\Truss.Modeling.Domain.csproj" />
      <ProjectReference Include="..\Truss.Modeling.Infrastructure\Truss.Modeling.Infrastructure.csproj" />
      <ProjectReference Include="..\Truss.Tests.XunitHelpers\Truss.Tests.XunitHelpers.csproj" />
    </ItemGroup>
</Project>
