<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Serilog" Version="[4, )" />
        <PackageReference Include="Serilog.AspNetCore" Version="[6, )" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Truss.AspNetCore\Truss.AspNetCore.csproj" />
      <ProjectReference Include="..\Truss.Modeling.Installation\Truss.Modeling.Installation.csproj" />
      <ProjectReference Include="..\Truss\Truss.csproj" />
    </ItemGroup>

</Project>
