<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <Title>Truss.Testing.Dsl</Title>
        <Description>Helps create domain specific languages and fixtures for testing</Description>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Castle.Core" Version="[5, 6)" />
        <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="[1, 9)" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="[1.0.0, 9)" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="[2.0.0, 9)" />
    </ItemGroup>
</Project>
