<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks Condition="'$(OS)' == 'Windows_NT'">net6.0;net7.0;net8.0;net461;net48</TargetFrameworks>
        <TargetFrameworks Condition="'$(OS)' != 'Windows_NT'">net6.0;net7.0;net8.0</TargetFrameworks>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net461' or '$(TargetFramework)' == 'net47' or '$(TargetFramework)' == 'net48'">
        <PackageReference Include="MediatR" Version="9.0.0" />
        <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="[7.0.0, )" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="[1, 5)" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net6.0' or '$(TargetFramework)' == 'net7.0' or '$(TargetFramework)' == 'net8.0'">
        <PackageReference Include="MediatR" Version="[12.0.0, )" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="[7.0.0, )" />
        <PackageReference Include="Newtonsoft.Json" Version="[12.0.1, )" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Truss.Modeling.Application\Truss.Modeling.Application.csproj" />
        <ProjectReference Include="..\Truss.Modeling.Area\Truss.Modeling.Area.csproj" />
        <ProjectReference Include="..\Truss.Modeling.Endpoints\Truss.Modeling.Endpoints.csproj" />
        <ProjectReference Include="..\Truss.Modeling.Module\Truss.Modeling.Module.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="DefaultServices\" />
    </ItemGroup>
</Project>
