<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="[1, )" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Truss.Modeling.Application\Truss.Modeling.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Truss.Modeling.Application\Truss.Modeling.Application.csproj" />
    </ItemGroup>
</Project>
