<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.assert" Version="[1, )" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Truss.Monads.Results\Truss.Monads.Results.csproj" />
  </ItemGroup>
</Project>