<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="MediatR" Version="[12.0.1, )" />
    <PackageReference Include="Newtonsoft.Json" Version="[3.5.8, 14)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Truss.Monads.Results.Extensions.Fluent\Truss.Monads.Results.Extensions.Fluent.csproj" />
  </ItemGroup>
</Project>