<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="MediatR" Version="[12.0.1, )" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="[6, )" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="[1, )" />
        <PackageReference Include="Newtonsoft.Json" Version="[12.0.1, )" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Truss.Modeling.Application\Truss.Modeling.Application.csproj" />
      <ProjectReference Include="..\Truss.Modeling.Domain\Truss.Modeling.Domain.csproj" />
      <ProjectReference Include="..\Truss.Modeling.Installation\Truss.Modeling.Installation.csproj" />
    </ItemGroup>

</Project>
