<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Truss.Testing.DomainSpecificLanguage\Truss.Testing.DomainSpecificLanguage.csproj" />
        <ProjectReference Include="..\Truss.Testing.Dsl.Analyzers\Truss.Testing.Dsl.Analyzers.csproj"
                          OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
    </ItemGroup>

</Project>
