<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <Protobuf Include="Protos\greet.proto" GrpcServices="Server"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Grpc.AspNetCore" Version="2.52.0"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ExampleApplication.Protobufs\ExampleApplication.Protobufs.csproj" />
    </ItemGroup>

</Project>
