<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Version>0.0.1-alpha-3</Version>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Truss.Monads.Results.Extensions.Fluent.SourceGenerator\Truss.Monads.Results.Extensions.Fluent.SourceGenerator.csproj"
                          outputItemType="Analyzer"
                          ReferenceOutputAssembly="false" 
        />
        <ProjectReference Include="..\Truss.Monads.Results\Truss.Monads.Results.csproj" />
    </ItemGroup>

</Project>
