<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\Truss.Modeling.Installation\Truss.Modeling.Installation.csproj" />
      <ProjectReference Include="..\Truss\Truss.csproj" />
    </ItemGroup>

</Project>
