<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.0.1</Version>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Truss.Monads.Results\Truss.Monads.Results.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="xunit.assert" Version="2.0.0" />
  </ItemGroup>
</Project>