<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Truss.Monads.Results.Extensions.Fluent\Truss.Monads.Results.Extensions.Fluent.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MediatR.Contracts" Version="[1.0.1, 3)" />
    <PackageReference Include="Newtonsoft.Json" Version="[12.0.1, 14)" />
  </ItemGroup>
</Project>