<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Castle.Core" Version="5.1.1" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.0" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="Microsoft.CodeAnalysis">
            <HintPath>..\..\..\..\.nuget\packages\microsoft.codeanalysis.common\4.8.0\lib\netstandard2.0\Microsoft.CodeAnalysis.dll</HintPath>
        </Reference>
        <Reference Include="Microsoft.CodeAnalysis.CSharp">
            <HintPath>..\..\..\..\.nuget\packages\microsoft.codeanalysis.csharp\4.8.0\lib\netstandard2.0\Microsoft.CodeAnalysis.CSharp.dll</HintPath>
        </Reference>
        <Reference Include="Microsoft.Extensions.DependencyInjection">
            <HintPath>..\..\..\..\.nuget\packages\microsoft.extensions.dependencyinjection\8.0.0\lib\net8.0\Microsoft.Extensions.DependencyInjection.dll</HintPath>
        </Reference>
        <Reference Include="System.Collections.Immutable">
            <HintPath>..\..\..\..\.nuget\packages\system.collections.immutable\7.0.0\lib\netstandard2.0\System.Collections.Immutable.dll</HintPath>
        </Reference>
    </ItemGroup>

</Project>
