<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="[1.0.0, )" />
        <ProjectReference Include="..\Truss.Monads.Results.Extensions.Fluent.SourceGenerator\Truss.Monads.Results.Extensions.Fluent.SourceGenerator.csproj"
                          outputItemType="Analyzer"
                          ReferenceOutputAssembly="false" 
        />
        <ProjectReference Include="..\Truss.Monads.Results\Truss.Monads.Results.csproj" />
    </ItemGroup>

</Project>
