<Project>
    <PropertyGroup>
        <TargetFrameworks>net8.0;</TargetFrameworks>
        <BuildNumber>$([System.DateTime]::Now.ToString("yyyyMMddHHmm"))</BuildNumber>
        <Version>0.0.2-alpha.$(BuildNumber)</Version>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>true</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup Condition="'$([System.String]::new($(MSBuildProjectName)).Contains(`.Modeling`))' == 'true'">
        <TargetLayer>Modeling</TargetLayer>
    </PropertyGroup>

    <PropertyGroup Condition="'$([System.String]::new($(MSBuildProjectName)).Contains(`.Monads`))' == 'true'">
        <TargetLayer>Modeling</TargetLayer>
    </PropertyGroup>

    <PropertyGroup Condition="'$([System.String]::new($(MSBuildProjectName)).Contains(`Testing`))' == 'true'">
        <TargetLayer>Modeling</TargetLayer>
    </PropertyGroup>

    <PropertyGroup Condition="'$([System.String]::new($(MSBuildProjectName)).Contains(`AspNetCore`))' == 'true'">
        <TargetLayer>Infrastructure</TargetLayer>
    </PropertyGroup>

    <PropertyGroup Condition="'$([System.String]::new($(MSBuildProjectName)).Contains(`Infrastructure`))' == 'true'">
        <TargetLayer>Infrastructure</TargetLayer>
    </PropertyGroup>

    <PropertyGroup Condition="'$([System.String]::new($(MSBuildProjectName)).Equals(`Truss`))' == 'true'">
        <TargetLayer>Infrastructure</TargetLayer>
    </PropertyGroup>

    <PropertyGroup Condition="'$([System.String]::new($(MSBuildProjectName)).EndsWith(`.Protos`))' == 'true'">
        <TargetLayer>Modeling</TargetLayer>
    </PropertyGroup>

    <PropertyGroup Condition="'$([System.String]::new($(MSBuildProjectName)).Contains(`Tests`))' == 'true'">
        <TargetLayer>Tests</TargetLayer>
    </PropertyGroup>

    <PropertyGroup Condition="'$([System.String]::new($(MSBuildProjectName)).EndsWith(`SourceGenerator`))' == 'true'">
        <TargetLayer>SourceGenerator</TargetLayer>
    </PropertyGroup>

    <PropertyGroup Condition="'$([System.String]::new($(MSBuildProjectName)).StartsWith(`ExampleApplication`))' == 'true'">
        <TargetLayer>ExampleApplication</TargetLayer>
    </PropertyGroup>

    <PropertyGroup Condition="'$(TargetLayer)' == 'Modeling'">
        <TargetFrameworks>netstandard2.0;</TargetFrameworks>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <PropertyGroup Condition="'$(TargetLayer)' == 'Protobuf'">
        <TargetFrameworks>netstandard2.0;</TargetFrameworks>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    
    <PropertyGroup Condition="'$(TargetLayer)' == 'Infrastructure'">
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <PropertyGroup Condition="'$(TargetLayer)' == 'Tests'">
        <IsTestProject>true</IsTestProject>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <PropertyGroup Condition="'$(TargetLayer)' == 'ExampleApplication'">
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <PropertyGroup Condition="'$(TargetLayer)' == 'SourceGenerator'">
        <TargetFrameworks>netstandard2.0;</TargetFrameworks>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <IsRoslynComponent>true</IsRoslynComponent>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    
    <ItemGroup Condition="'$(TargetLayer)' == 'SourceGenerator'">
        <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="8.0.0" />
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.3.0"/>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.3.0"/>
    </ItemGroup>

</Project>
