<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
        <Protobuf Include="Protos\greet.proto" GrpcServices="Server"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Grpc.AspNetCore" Version="2.52.0"/>
        <PackageReference Include="MediatR" Version="12.2.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ExampleApplication.Module1\ExampleApplication.Module1.csproj" />
        <ProjectReference Include="..\ExampleApplication.Module2\ExampleApplication.Module2.csproj" />
        <ProjectReference Include="..\ExampleApplication.Protos\ExampleApplication.Protos.csproj" />
        <ProjectReference Include="..\Truss.AspNetCore\Truss.AspNetCore.csproj" />
        <ProjectReference Include="..\Truss\Truss.csproj" />
        <ProjectReference Include="..\Truss.Modeling.Application\Truss.Modeling.Application.csproj" />
        <ProjectReference Include="..\Truss.Modeling.Installation\Truss.Modeling.Installation.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="Endpoints.cs" />
    </ItemGroup>

</Project>
