<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Truss.Modeling.Application\Truss.Modeling.Application.csproj" />
      <ProjectReference Include="..\Truss.Modeling.Domain\Truss.Modeling.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MediatR" Version="12.1.1" />
    </ItemGroup>

</Project>
