name: Publish NuGets

on:
  push:
    branches:
      - main
      - master
      - releases/*
      - features/*
  workflow_dispatch:

permissions:
  contents: write

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Detect source changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            src:
              - 'src/**/*.cs'
              - 'src/**/*.fs'
              - 'src/**/*.vb'

  publish:
    runs-on: ubuntu-latest
    needs: 
      - detect-changes
    if: needs.detect-changes.outputs.src == 'true'
    defaults: 
      run: 
        shell: bash
        working-directory: './src'
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.2.0
        with:
          versionSpec: '6.3.x'

      - name: Determine Version
        id: version_step # step id used as a reference for output values
        uses: gittools/actions/gitversion/execute@v3.2.0
        with:
          useConfigFile: true
          configFilePath: './.github/config/GitVersion.yml'
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore -p:Version=${{ steps.version_step.outputs.semVer }}

      - name: Run Tests
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Pack Release
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: dotnet pack --configuration Release --no-build --output ./nupkgs -p:Version=${{ steps.version_step.outputs.majorMinorPatch }} 

      - name: Pack Pre-Release
        if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master'
        run: dotnet pack --configuration Release --no-build --output ./nupkgs -p:PackageVersion=${{ steps.version_step.outputs.SemVer }}

      - name: Verify NuGet packages exist
        run: |
          echo "Checking for built NuGet packages..."
          if ls ./nupkgs/*.nupkg 1> /dev/null 2>&1; then
            echo "✅ Found NuGet packages."
            ls ./nupkgs/*.nupkg
          else
            echo "🚨 No NuGet packages found. Failing build."
            exit 1
          fi

      - name: Push packages to Staging Feed
        run: |
          for package in ./nupkgs/*.nupkg
          do
            echo "Pushing $package..."
            dotnet nuget push "$package"  \
              --source "${{ secrets.PRERELEASE_NUGET_SOURCE }}"   \
              --api-key "${{ secrets.PRERELEASE_NUGET_API_KEY }}"  \
              --skip-duplicate
          done


      - name: Create Git Tag when Release
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          TAG=${{ steps.version_step.outputs.majorMinorPatch }}
          echo "Tagging commit with $TAG"
          git tag $TAG
          git push origin $TAG
